spring.application.name=RelatoriosJava
spring.datasource.url=jdbc:mysql://localhost:3306/jpajava
spring.datasource.username=root
spring.datasource.password=00000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=never

spring.thymeleaf.cache=false